.github/workflows/apply-staging.yml
changing references from master branch to main
=> ci: change branch name

.devcontainer/Dockerfile, .devcontainer/README.md, .devcontainer/devcontainer.json, aws/etl_lambdas/policies.tf, env/staging/ecr/.terraform.lock.hcl, env/staging/etl_lambda/.terraform.lock.hcl, env/staging/network/.terraform.lock.hcl, env/staging/s3/.terraform.lock.hcl
* Adds an IAM policy for ETL Lambdas
* Adds a devcontainer
Closes #9
=> fix: create IAM policy for ETL Lambdas

aws/etl_lambdas/inputs.tf, aws/etl_lambdas/lambdas.tf, aws/modules/lambda/inputs.tf, aws/modules/lambda/lambda.tf, env/staging/etl_lambda/terragrunt.hcl
- Adds the ability to configure extra environment variables on the
lambdas
- Adds the ability to specify the memory size of the lambda
=> feat: add env variable config and memory size

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/policy/no-changes.rego
* Policy that checks if there are changes to resources or outputs as part of a `terraform plan`.
* Adds `opa` to devcontainer.
Related #6
=> feat: add TF rego "no changes" policy 

aws/etl_lambdas/policies.tf, env/staging/etl_lambda/terragrunt.hcl
- rename ENV to ENVIRONMENT
- add missing policies
=> fix: policies and env variables

aws/etl_lambdas/policies.tf
=> fix: remove sids whcih break apply

.github/workflows/policy/resource-changes.rego, .github/workflows/pull-request.yml
* Shows count of TF create, update and delete actions in the PR comment.
* Makes the success/failure of the format and plan more obvious.
=> feat: show TF plan resource change count

.github/workflows/apply-production.yml, .github/workflows/lint.yml, .github/workflows/pull-request.yml, env/production/ecr/terragrunt.hcl, env/production/env_vars.hcl, env/terragrunt.hcl
- Add ECR in Production (this is needed so we can push an image for
later infra work)
- Pull out linting code to it's own repo to make the pull-request.yml
workflow easier to read
- Add a workflow for deploying to production
- Refactoring PR so that it can handle multiple environments
=> feat: Add production environment step 1

.github/workflows/apply-production.yml, .github/workflows/pull-request.yml
Enables github workflows around production and releases v1.0.2 to production
=> ci: release 1.0.2 to production

.github/workflows/pull-request.yml, env/production/network/terragrunt.hcl, env/production/s3/terragrunt.hcl
Deploy s3 and network to production
=> feat: deploy s3 and vpc to production

.github/workflows/apply-production.yml
=> fix: set prod version step was borked

env/production/etl_lambdas/terragrunt.hcl
Increase the memory size on prod lambdas
=> feat: increase lambda memory to 10 gigs in prod

.devcontainer/devcontainer.json
This adds YAML linting to the devcontainer.
=> feat: add VS Code YAML extenstion

aws/modules/lambda/efs.tf, aws/modules/lambda/lambda.tf
This allows the lambda to write to a file storage that can handle the
amount of data we are writing to disk
=> feat: add an elastic file storage to lambdas

aws/etl_lambdas/policies.tf, aws/modules/lambda/efs.tf, aws/modules/lambda/outputs.tf
Allow the lambdas to write, and mount efs filesystems
=> feat: allow lambda exec role to use efs

aws/etl_lambdas/inputs.tf, aws/etl_lambdas/lambdas.tf, aws/modules/lambda/efs.tf, aws/modules/lambda/inputs.tf, env/staging/etl_lambdas/terragrunt.hcl
Attach the Elastic File Storage to the new Network Security Group so the lambdas can talk to it.
=> feat: attach EFS to the new SG

env/production/etl_lambdas/terragrunt.hcl
This deploys theimage that reads from the TMP_FOLDER environment
variable
=> fix: deploy desired image

.github/workflows/pull-request.yml, aws/sqs/outputs.tf, aws/sqs/sqs.tf, env/staging/sqs/terragrunt.hcl
Please note there should be no changes to do on infra through this PR as
this is part of a migration from our Terraform staging repo into
Terragrunt
=> feat: Importing SQS and Managed Key into TG

.github/workflows/pull-request.yml, aws/dynamodb/aggregate_metrics_table.tf, aws/dynamodb/raw_metrics.table.tf, env/staging/dynamodb/terragrunt.hcl
- adds aggregate_metrics table
- adds raw_metrics table
**Please note:** This should not modify state as changes were done
locally.
=> feat: import the metrics tables

aws/backoff_retry_lambda/iam_policies.tf
Fixes the name conflict we had with the policy
=> fix: pick a unique name

aws/backoff_retry_lambda/backoff_retry.tf, aws/modules/lambda/lambda.tf, aws/network/efs_sg.tf, aws/network/lambda_sg.tf
First pass ignoring Checkov warnings that do not apply.
None
Related: #2
=> feat: ignore Checkov warnings that do not apply

aws/ecr/ecr.tf, aws/modules/s3/s3.tf, aws/network/flow_logs.tf
Includes VPC flow log, CloudWatch log group and IAM role/policy to write logs.
* Create VPC flow log
* Create CloudWatch log group
* Create IAM role/policy to write logs
Related #2
=> feat: add VPC flow logs

aws/ecs/ecs.tf, aws/modules/ecs_task/cloudwatch.tf, aws/modules/ecs_task/inputs.tf, env/staging/ecs/task-definitions/metrics.json
Adds cloudwatch events to trigger ETL jobs
Move from hello world to actual images
No guarantee that this will work, and is still very much a WIP and testing will be required in the console.
=> feat: use real images, add scheduled tasks

aws/ecs/cloudwatch_event_role.tf, aws/ecs/ecs.tf, aws/modules/ecs_task/cloudwatch.tf, aws/modules/ecs_task/inputs.tf
Add a role that can run tasks and pass roles.
=> feat: add a role for the schedule task

aws/ecs/ecs.tf
=> fix: change to rates from cron

aws/modules/ecs_task/task.tf
Removes a service in favour of a scheduled task
=> fix: remove service in favour of scheduled task

.github/workflows/lambda-tests.yml, env/production/aggregate_metrics_lambda/.terraform.lock.hcl, env/production/aggregate_metrics_lambda/lambda/aggregate_values.js, env/production/aggregate_metrics_lambda/lambda/aggregate_values.test.js, env/production/aggregate_metrics_lambda/lambda/create_metric.js, env/production/aggregate_metrics_lambda/lambda/create_metric.test.js, env/production/aggregate_metrics_lambda/lambda/jest.config.js, env/production/aggregate_metrics_lambda/lambda/lambda_validate_deploy.rb, env/production/aggregate_metrics_lambda/lambda/package-lock.json, env/production/aggregate_metrics_lambda/lambda/package.json, env/production/aggregate_metrics_lambda/terragrunt.hcl
No TF changes expected except:
- aws_iam_policy.vpc_networking from wildcard to specific resource
- aggregate_metrics lambda filename and publish flag
=> feat: production aggregate metrics migrating into TG repo

aws/ecr/ecr.tf, aws/ecr/outputs.tf
Adds a container repo for the key server metrics etl task and the
appstore metrics etl task.
Expected to create two new ECR Repositories
=> feat: add new container repositories

aws/ecs/inputs.tf, aws/ecs/server_metrics_etl.tf, env/staging/ecs/task-definitions/server_metrics.json, env/staging/ecs/terragrunt.hcl
add the server events endpoint to the server metrics tasks
=> feat: add a server events endpoint

aws/modules/ecs_task/cloudwatch.tf
We want this to update scheduled tasks
=> fix: stop ignoring changes to the task def for scheduled task

aws/ecs/server_metrics_etl.tf
Use the proper ECR repo for the server metrics task.
=> fix: use proper ECR repo for server metrics

env/production/ecs/terragrunt.hcl
Changes to Server_metrics ECR Repo so it uses the correct one
Changes to day over day alarm
Deployment of new tag to Production Tasks
=> feat: deploy latest container image and v1.0.42

env/staging/ecs/task-definitions/metrics.json, env/staging/ecs/task-definitions/server_metrics.json
This was achieved by:
1) Sorting the JSON file
2) Adding all default values that TF expected
Closes #182
=> feat: no change taskdef no longer show in plan

env/production/aggregate_metrics_lambda/lambda/aggregate_values.js, env/production/aggregate_metrics_lambda/lambda/aggregate_values.test.js
Production didn't have the new lambda code, this change will rectify that. Only change in the TF plan should be aggregate_metrics lambda.
=> chore: deploy error metrics lambda to production

env/production/aggregate_metrics_lambda/terragrunt.hcl, env/production/cloudwatch_alarms/terragrunt.hcl, env/production/create_metrics_lambda/terragrunt.hcl, env/staging/aggregate_metrics_lambda/terragrunt.hcl, env/staging/cloudwatch_alarms/terragrunt.hcl, env/staging/create_metrics_lambda/terragrunt.hcl
No longer collecting debug metrics for the app.
* Create API gateway and DynamoDB WCU CloudWatch alarms
* Redeploy API gateway
=> chore: re-enable API gateway and DynamoDB alarms

README.md
Add English/French README.md content.
=> docs: add English/French readme

aws/api_gateway/inputs.tf, aws/api_gateway/waf.tf, env/production/api_gateway/terragrunt.hcl, env/staging/api_gateway/terragrunt.hcl
Since SizeRestrictions_BODY has been excluded from the WAF rules, this PR introduces the capability to configure the body size limit by setting a flag.
=> feat: new custom rule that has a configurable body size limit

env/production/create_metrics_lambda/lambda/create_metric.js, env/production/create_metrics_lambda/lambda/create_metric.test.js, env/staging/create_metrics_lambda/lambda/create_metric.js, env/staging/create_metrics_lambda/lambda/create_metric.test.js
Save large payloads to S3 for debugging purposes
=> feat: stage pr metrics lambda

aws/api_gateway/waf.tf
Update WAF ACL to block traffic unrelated to metrics submission.
=> feat: block unexpected traffic

aws/api_gateway/waf.tf
Block all requests containing query strings since it's not required for processing metrics payloads
=> feat: block all requests containing query strings

aws/api_gateway/waf.tf
Mandatory text transformation statement missing.
=> fix: add missing waf acl statement

env/production/ecs/terragrunt.hcl
Related: cds-snc/covid-alert-metrics-etl#176
=> feat: release ETL string manipulation fix
