aws/etl_lambdas/inputs.tf
aws/etl_lambdas/policies.tf
env/staging/etl_lambda/terragrunt.hcl

- Rename the input variable in etl_lambda from `create_csv_ecr_arn` to `create_csv_repository_arn` to better represent what it is.
- inject the variable into the etl_lambda module

fix: rename ecr_arn and inject it into etl_module

---

aws/etl_lambdas/policies.tf

I spelled dynamodb wrong, this pr fixes it.

fix: spelling mistake in dynamodb policy

---

aws/etl_lambdas/policies.tf

Apply the proper permission set to read a dynamodb table

fix: allow role to read dynamodb

---

.devcontainer/Dockerfile

This will let us use our local `git config core.editor "vim"` setting in the devcontainer.

feat: add vim to devcontainer

---

.github/workflows/policy/no-changes.rego
.github/workflows/pull-request.yml

This checks the TF plan output to determine if there are any resource or output changes.  This is then used to control if the plan comment should be added to the PR.
Also includes a fix to prevent the terragrunt exit code from being hidden by the pipe to tee.
Closes #6 
Closes #15

feat: use OPA to check for TF plan changes

---

aws/network/nacl.tf

This removes the repeated subnet update shown in TF plans.  This is explained in the [aws_default_network_acl docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_network_acl):
> Because Subnets are by default associated with the Default Network ACL, any non-explicit association will show up as a plan to remove the Subnet.
Fixes #16

fix: explicitly set default Network ACL subnets

---

aws/network/efs_sg.tf
aws/network/lambda_sg.tf
aws/network/outputs.tf
aws/network/vpc.tf

This is the first step in a multi pr process. 
First we are creating a network security group for an EFS and allowing ingress over port 2049 (NFS) so that things can talk to the EFS. 
We are also adding an egress rule to the Lambda SG so that it can talk to the new EFS SG. 
Next we'll be attaching the EFS into the new SG but the sg has to be there first.

feat: add network infra for efs

---

env/common/common_variables.tf
env/common/provider.tf
env/terragrunt.hcl

Use the file function instead of here docs for generated files, this allows us to get the benefit of syntax highlighting and autoformatting for our common files that are injected by terragrunt.

feat: use file function instead of heredocs

---

env/production/etl_lambdas/terragrunt.hcl

Wires up the new Network EFS SG to the ETL_Lambda module in production, we forgot to do that with the last build.

fix: wire up EFS SG in prod

---

aws/etl_lambdas/policies.tf

Attaches the CloudWatchLambdaInsightsExecutionRolePolicy role to the role used by the lambdas so we can enable Lambda Insights on these two lambdas. 
See: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-docker.html

feat: attach the lambda insights exec role to lambdas

---

aws/dynamodb/outputs.tf
aws/sqs/outputs.tf

Add outputs needed to migrate over the backoff retry lambda
This should only add new outputs

feat: Add required outputs

---

env/production/etl_lambdas/terragrunt.hcl

Instead of saving scan pages to a CSV we save to an in-memory data
structure

feat: Deploy in-memory scan

---

.github/workflows/s3-backup.yml

This provides an additional backup of the project's code if
GitHub and its backups are unavailable.
Related cds-snc/site-reliability-engineering#194

feat: backup branch to an S3 buckup daily

---

aws/backoff_retry_lambda/alarm.tf
aws/dynamodb/aggregate_metrics_table.tf

To improve the speed of the ETL script we are creating a global
secondary index on the identifier field.
This will allow us to run queries on that field instead of scanning the
entire db and then filtering on the identifier that we currently do.

feat: add a gsi on the identifier

---

.github/workflows/security-scan.yml

Scans the `*.tf` code for potential security problems.
Currently this does not fail the pipeline if security problems are found to give us time to address the failures.  Once that's taken care, this can be set to hard fail pipelines with security problems.
Related #2

feat: add Checkov Terraform static analysis

---

.github/workflows/pull-request.yml
aws/cloudwatch_alarms/api_gateway.tf
aws/cloudwatch_alarms/data_lookups.tf
aws/cloudwatch_alarms/inputs.tf
env/staging/cloudwatch_alarms/.terraform.lock.hcl
env/staging/cloudwatch_alarms/terragrunt.hcl

Staging alarm migrated from [cds-snc/covid-alert-server-stating-terraform](https://github.com/cds-snc/covid-alert-server-stating-terraform).
This should not cause any resources to be created as everything was imported locally with the following commands:
```terraform
terragrunt import aws_cloudwatch_metric_alarm.metrics_api_gateway_500_errors_above_threshold metrics-api-gateway-errors-above-threshold
terragrunt import aws_cloudwatch_metric_alarm.metrics_api_gateway_max_invocations_threshold[0] metrics-api-gateway-above-maximum-invocations
terragrunt import aws_cloudwatch_metric_alarm.metrics_api_gateway_max_latency_threshold metrics-api-gateway-above-maximum-latency
terragrunt import aws_cloudwatch_metric_alarm.metrics_api_gateway_min_invocations_threshold …
```

feat: migrate staging API gateway CloudWatch alarms

---

aws/cloudwatch_alarms/api_gateway.tf
aws/cloudwatch_alarms/inputs.tf
env/production/cloudwatch_alarms/.terraform.lock.hcl
env/production/cloudwatch_alarms/terragrunt.hcl
env/staging/cloudwatch_alarms/.terraform.lock.hcl
env/staging/cloudwatch_alarms/terragrunt.hcl

Adds two alarms related to the iOS metrics to staging incident.
1. Catch 4xx errors which can be generated by a bad metrics payload.
2. Catch traffic fluctuations from the expected daily norm.
1. Two new alarms.
2. Recreate existing 5xx alarm because of name change.
Closes #71
Closes #72

feat: alarms for metric traffic problems

---

env/production/cloudwatch_alarms/terragrunt.hcl

Alarms should only be deployed to production from a tagged version of the module.  This resulted in the prod alarm being created before it was expected.
1. Remove 4xx and anomaly detection alarms from prod
2. Recreate 5xx alarm with its old name
Related #71 
Related #72

fix: alarms should deploy from tagged version

---

.github/workflows/lint.yml
.github/workflows/scripts/check-terragrunt-tagged.sh

This is to catch cases that caused the incident where an untagged
module was deployed accidentally to production by a merge to main.
None
Closes #82

fix: check prod Terragrunt config use tags

---

aws/cloudwatch_alarms/api_gateway.tf

The anomaly band AWS is calculating for the API gateway works in
Staging but for Production, it doesn't properly anticipate the UTC
midnight spike in traffic.  As a result, this alarm would trigger daily.
Related #71

fix: remove anomaly detection CloudWatch alarm

---

aws/network/flow_logs.tf

The resources for the VPC flow log IAM policy needs permission to
act on the log streams.
* Update IAM policy for VPC flow log
Related #92

fix: VPC flow log policy resource

---

Makefile
aws/backoff_retry_lambda/iam_policies.tf
aws/etl_lambdas/policies.tf
aws/modules/s3/s3.tf

* IAM policy updates to reference specific resources where possible.
* Block all public access to S3 buckets.
* Makefile added with common commands.
1. Add two S3 public access blocks for the masked and unmasked metrics CSVs.
**Note:** the policy change was done locally during testing.
Closes #2

feat: Checkov IAM policy fixes and block S3 public access

---

.github/workflows/sync-labels.yml

Adds the sync label workflow to synchronize labels between EN server projects.
Closes #17

feat: sync labels between server projects

---

aws/ecs/ecs.tf
aws/ecs/task_execution_role.tf

Set the CPU units to 512 and memory to 1024 in staging (this might be changed later).
Update the name on task execution policy so it doesn't clash with existing policy (that will be removed later)

fix: cpu/mem units, policy name

---

aws/network/vpc.tf
env/staging/dynamodb/.terraform.lock.hcl
env/staging/sqs/.terraform.lock.hcl

ca-central-1d does not support fargate and unforuntaly that's the AZ
that our private subnet was originally added to.
This PR will remove and recreate the private subnet, it might touch
other network resources but shouldn't affect anything outside of the
network module.

feat: move private subnet to az that supports ECS

---

aws/ecs/ecs.tf

Use the proper expression format for the schedule_expression.
See: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule#schedule_expression

fix: use proper schedule_expression

---

aws/ecs/container_execution_role.tf
env/staging/ecs/.terraform.lock.hcl

This is needed so that the metrics github action can deploy images to ecs

fix: add ecs task principal to container_execution_role

---

aws/ecs/ecs.tf
aws/ecs/input.tf
aws/modules/ecs_task/inputs.tf
env/staging/ecs/task-definitions/metrics.json
env/staging/ecs/terragrunt.hcl

Adds an `unmasked_image_tag` an a `masked_image_tag` to the ECS module.
This allows us to specify the images that we want to deploy.
Set image tags to latest in staging.

fix: add image tag variables for ecs task

---

aws/ecs/ecs.tf
env/staging/ecs/task-definitions/metrics.json

ECS tasks need to know the name of the bucket they are saving too.

fix: add bucket names to the task definition

---

aws/ecs/cloudwatch_event_role.tf

Allow the etl-st-cw-role to PassRole to the container execution role instead of the task execution role.

fix: use container exec role instead of task

---

aws/ecs/cloudwatch_event_role.tf

Re-adds the ability to pass the task execution role on, as I never should have removed it in the first place.

fix: adding back the task execution role

---

aws/network/data_lookups.tf
aws/network/vpc.tf

This attempts to fix the error deleting Lambda ENIs using subnet due to resource not being available during rebuild

fix: add lambda policy dependency to vpc

---

aws/modules/ecs_task/cloudwatch.tf
env/production/cloudwatch_alarms/terragrunt.hcl

There is a new app metrics traffic pattern that is causing a
spike of save-metrics API gateway requests at midnight EST.
This is exceeding the `save-metrics` Lambda account max concurrency
and causing AWS to throttle Lambda invocations, which returns a
500 error to the phone.
Since phones will attempt to re-submitted failed metrics payloads
this means no metrics data is being lost.
* Increase metrics API gateway 5xx alarm threshold to 1,000.
Closes #124

feat: increase API gateway 5xx alarm threshold

---

.github/workflows/pull-request.yml

Will give the ability to launch the pull request workflow on demand.
Use case: Manually trigger terraform plan workflow steps without requiring an empty commit or finding a previous run. Allows you to select which branch to execute the workflow against

feat: add ability to manually start terraform plans from gh actions

---

aws/cloudwatch_alarms/api_gateway.tf
env/staging/cloudwatch_alarms/terragrunt.hcl

Updating the 5xx alarm period to 10 minutes.  The idea being this alarm will now catch cases were we see a large number of sustained failures, which would indicate there is an app or infrastructure problem.
* Staging `metrics_api_gateway_500_errors_above_threshold` alarm update.

feat: increase API gateway 5xx alarm period 

---

aws/ecs/cloudwatch_event_role.tf

We forgot to ad the server_appstore_task_execution_role to the passrole
policy.

fix: allow the passing of the new task exec role

---

aws/cloudwatch_alarms/api_gateway.tf
aws/cloudwatch_alarms/inputs.tf
env/production/cloudwatch_alarms/terragrunt.hcl
env/staging/cloudwatch_alarms/terragrunt.hcl

Testing an alarm that will trigger when there is more than a 20% traffic change between 2 days.  Currently it does not notify of alarm conditions.
New CloudWatch alarm.
Closes #71

feat: CloudWatch alarm for change in traffic

---

.github/workflows/apply-staging.yml
.github/workflows/pull-request.yml
aws/ecs/inputs.tf
aws/ecs/secretsmanager_role.tf
env/staging/ecs/task-definitions/server_metrics.json
env/staging/ecs/terragrunt.hcl

fix: retrieve metrics_token secret value from github secrets

---

.github/workflows/apply-production.yml
.github/workflows/apply-staging.yml
.github/workflows/pull-request.yml
env/production/ecs/task-definitions/server_metrics.json
env/staging/ecs/terragrunt.hcl

- TG will now automatically inject metrics_token from github secrets. 
- PR ECS now also contains the new taskdefinition
fixes #145

fix: TG will now automatically inject metrics_token from secrets. 

---

aws/ecs/cloudwatch_event_role.tf
aws/ecs/container_execution_role.tf
aws/ecs/server_metrics_etl.tf
aws/ecs/task_execution_policy_documents.tf
aws/ecs/task_execution_roles.tf

Remove the Server_metrics role and replace with the old server_appstore
role
Attach the secretsmanager_etl_policies to a new container exec role for
the server metrics task

fix: attach ReadSecrets policy to container exec

---

aws/ecs/cloudwatch_event_role.tf

fix: add server metric container role to cloudwatch event role

---

aws/aggregate_metrics_lambda/iam_policies.tf
aws/cloudwatch_alarms/error_metrics.tf
aws/cloudwatch_alarms/inputs.tf
env/production/cloudwatch_alarms/terragrunt.hcl
env/staging/aggregate_metrics_lambda/lambda/aggregate_values.js
env/staging/aggregate_metrics_lambda/lambda/aggregate_values.test.js
env/staging/cloudwatch_alarms/terragrunt.hcl

aggregate_metrics lambda will now send error metrics to cloudwatch. This PR will create a new metric alarm based on the below
3 occurrences of error-500-qr-parse will generate a critical alarm
1 occurrences of error-500-qr-parse will generate a warning alarm
Closes #153

Send error metrics to cloudwatch metrics and generation alarms

---

aws/cloudwatch_alarms/api_gateway.tf

Update traffic change alarm to use API gateway's `Count` metric.
Update the CloudWatch alarm.
Related #71

fix: use API gateway "Count" metric

---

aws/ecs/server_metrics_etl.tf

Set the proper container execution role for the server metrics task so
it can access the metrics_token secret

fix: container execution role

---

aws/ecs/container_execution_role.tf

Attach the proper role to the server metrics container execution role

fix: allow server metrics ce to do things

---

aws/cloudwatch_alarms/api_gateway.tf

A 20% change in traffic over 2 days will now trigger an alarm. This is meant to catch cases where suddenly a large number
of phones stop sending us data.
Add warning alarm action.
Closes #168

feat: metric traffic change alarm warning action

---

aws/modules/ecs_task/task.tf
env/staging/ecs/task-definitions/metrics.json
env/staging/ecs/task-definitions/server_metrics.json

Fargate does not allow you to specify the host or sourcePath for a bind mount
Also enabling ptrace support since falco requires it when running on fargate

fix: remove host_path and enable ptrace

---

aws/modules/ecs_task/task.tf

TF apply failing due to volume declaration in a fargate task

fix: remove falco volume definition from tf task

---

aws/modules/ecs_task/task.tf

This failed last time because i didn't notice two volumes still declared a host_path. Hopefully this fixes the volume issues.

fix: reintroduce ecs volume and remove missed host_path

---

env/staging/ecs/task-definitions/metrics.json
env/staging/ecs/task-definitions/server_metrics.json

Missing link to get falco running that was verified via click ops

chore: remove elevated container priviledges

---

.github/workflows/pull-request.yml

This will keep the CI updated with the latest non-breaking version of the action.

chore: use v1 release of Terrafom plan action

---

env/staging/ecs/task-definitions/metrics.json
env/staging/ecs/task-definitions/server_metrics.json

This is required since latest kernel headers are only available in this branch

chore: bump falco to master branch

---

env/staging/api_gateway/terragrunt.hcl
env/staging/create_metrics_lambda/terragrunt.hcl
env/variables.auto.tfvars

Having API stage and resource with different endpoints (create_metrics vs save-metrics) is too risky. Restoring the path back to "save-metrics"

chore: restore original api name

---

aws/create_metrics_lambda/iam_policies.tf

AWS managed policy was missing that defines the minimum required to run lambdas. This has been added and the unnecessary customer managed policies have been removed since they're not redundant.

fix: lambda execution role has correct permissions

---

.github/workflows/apply-production.yml
.github/workflows/apply-staging.yml
.github/workflows/pull-request.yml
env/production/api_gateway/terragrunt.hcl
env/staging/api_gateway/terragrunt.hcl

The Route53 hosted zone name is not secret and can be set as a plaintext input to the `api_gateway` module.
Related #148

feat: set API gateway route53 zone name with input

---

.gitignore
env/terragrunt.hcl

This will use any variables defined in an optional `secrets_env_vars.hcl` for Terragrunt commands.  The file has the same structure as the `env_vars.hcl` file:
```hcl
inputs = {
var_name = "some-super-secret-value"
}
```
API gateway deploy recreate in Staging/Prod
Closes #148

feat: add local secrets environment variables

---

env/production/ecs/terragrunt.hcl

This addresses the bug with bad semantic versions
fixed in cds-snc/covid-alert-metrics-etl#169

fix: bump the Metrics ECS task image tag

---

aws/cloudwatch_alarms/error_metrics.tf

Since QR is not in production, this does not need to be a critical alarm that creates an OpsGenie alert.
**Note:** the production change to this alarm is because I've manually set it to warning, so the terraform is flipping it back to critical.

feat: set QR parse error alarm to warning topic

---

aws/ecs/appstore_metrics_etl.tf
aws/ecs/common_inputs.tf
aws/ecs/data_lookups.tf
aws/ecs/inapp_metrics_etl.tf
aws/ecs/server_metrics_etl.tf
aws/modules/ecs_task/cloudwatch.tf
aws/modules/ecs_task/inputs.tf
env/staging/ecs/terragrunt.hcl

This is to catch cases where the scheduled ETL tasks cause an error.
A new metric and CloudWatch alarm for each ETL task.
Closes cds-snc/covid-alert-metrics-etl#166

feat: add CloudWatch alarm for ECS task errors

---

aws/modules/ecs_task/cloudwatch.tf

Set the allowed number of ECS errors to `0`.
* Update the six ECS CloudWatch alarms.
* API gateway redeploy.
Related cds-snc/covid-alert-metrics-etl#166

fix: ECS error alarm should trigger if any errors

---

env/production/cloudwatch_alarms/terragrunt.hcl
env/staging/cloudwatch_alarms/terragrunt.hcl

This disables the max invocation alarm on the API gateway since
the app debug metrics will exceed this.
* Remove API gateway max invocation alarms
* Redeploy API gateway stage

chore: disable API alarms in prep for debug metrics

---

env/production/aggregate_metrics_lambda/terragrunt.hcl
env/production/create_metrics_lambda/terragrunt.hcl
env/staging/aggregate_metrics_lambda/terragrunt.hcl
env/staging/create_metrics_lambda/terragrunt.hcl

These alarms will trigger while we are capturing debug metrics from the app.  Currently these alarms have their SNS topic alarm action removed.
* Remove create and aggregate DynamoDB WCU alarms
* API gateway redeploy

chore: disable the DynamoDB WCU alarms

---

aws/cloudwatch_alarms/error_metrics.tf
aws/cloudwatch_alarms/inputs.tf
env/production/cloudwatch_alarms/terragrunt.hcl
env/staging/cloudwatch_alarms/terragrunt.hcl

Create feature flag to deactivate QR code CloudWatch alarms until the service is launched.

feat: feature flag to deactivate qr code alarms

---

README.md

* Fix anchor link to French content of README.
* Link directly to English/French specific content where available.

docs: fix French named anchor

---

aws/api_gateway/waf.tf

This is required due to the metrics payload growing to a size that exceeds this WAF rule that verifies that the request body size is at most 10,240 bytes.

fix: body size restriction waf rule excluded

---

aws/api_gateway/waf.tf

Too risky to introduce in block mode. Will deploy as a count and observe. Testing was successful

chore: don't block so we can observe

---

env/staging/create_metrics_lambda/lambda/create_metric.js
env/staging/create_metrics_lambda/lambda/create_metric.test.js

Corrects a bug where the metrics payload is being stringified excessively.

fix: correctly convert chunked payloads to string

---

env/staging/create_metrics_lambda/lambda/create_metric.js
env/staging/create_metrics_lambda/lambda/create_metric.test.js

Noticed large payloads still generating errors in staging, this was due to the byte calculation not taking into consideration that the payload would be converted to string prior to sending to dynamodb.
In-order to calculate the correct # of bytes being sent to dynamodb the payload needs to be converted into a string when doing the byte calculation.

fix: correctly calculate payload size

---

env/production/create_metrics_lambda/terragrunt.hcl

Still experiencing `ERROR Upload failed ValidationException: Item size has exceeded the maximum allowed size`. How we're calculating byte size and how aws is validating may not be exactly the same, so some trial and error will be needed
This PR will reduce the threshold to 200k.

feat: lower split payload threshold from 300k to 200k

---

env/staging/create_metrics_lambda/lambda/create_metric.js
env/staging/create_metrics_lambda/lambda/create_metric.test.js

Currently we're only looking at the payload length which is resulting in missing scenarios where the entire metric body is larger than DynamoDB can handle. This PR introduces changes that will calculate the entire body size to determine if a large payload should be split or dropped

refactor: include body when calculating request length

---

aws/s3/inputs.tf
aws/s3/outputs.tf
aws/s3/s3.tf
env/staging/s3/.terraform.lock.hcl

Create S3 bucket so error samples can be collected when payloads exceed the maximum dynamodb buffer size. This is to determine if these are legitimate payloads or invalid

feat: create s3 bucket

---

.gitignore
aws/create_metrics_lambda/create_metrics.tf
aws/create_metrics_lambda/iam_policies.tf
aws/create_metrics_lambda/inputs.tf
env/staging/create_metrics_lambda/lambda/create_metric.js
env/staging/create_metrics_lambda/lambda/create_metric.test.js
env/staging/create_metrics_lambda/terragrunt.hcl

If payload is too large, store a copy in s3 so it can be validated for bugs in metrics generation.

feat: store error samples to s3

---

aws/s3/inputs.tf
aws/s3/s3.tf
env/production/create_metrics_lambda/lambda/create_metric.js
env/production/s3/terragrunt.hcl
env/staging/create_metrics_lambda/lambda/create_metric.js
env/staging/s3/terragrunt.hcl

Due to policy we will now only store s3 samples for 1 day to match the projects retention policies. S3 lifecycle rules are retroactive, so existing files will be deleted after 1 day.
This PR also adds:
- additional debug outputs to determine why large payloads are not being split.
- modified logging so the centralized logging bucket is used

feat: reduce s3 lifecycle and more debugs for large payloads

---

aws/create_metrics_lambda/create_metrics.tf
aws/create_metrics_lambda/inputs.tf
env/production/create_metrics_lambda/terragrunt.hcl
env/staging/create_metrics_lambda/lambda/create_metric.js
env/staging/create_metrics_lambda/lambda/create_metric.test.js
env/staging/create_metrics_lambda/terragrunt.hcl

Refactored to parse JSON formatted strings instead of assuming JSON.parse was already done at the API level.

refactor: parse json before trying to split

---

env/production/cloudwatch_alarms/terragrunt.hcl
env/staging/cloudwatch_alarms/terragrunt.hcl

The CloudWatch 4xx and 5xx alarm thresholds were too high and caused us to miss a large spike in 4xx errors that was caused by phones sending payloads that were being rejected by the WAF ACL request size body rule.
* Closes #236
* #239 
* #240 
* #241 
* #242

fix: lower API gateway 4xx/5xx alarm thresholds

---

.devcontainer/Dockerfile

The checkov install was failing due to missing OS packages. This is
likely due to a change in how a more recent version of checkov is
being released.

fix: add packages required to install checkov

---

aws/ecs/cloudwatch_events.tf
aws/ecs/ecs_events/ecs_events.py

Add logs for the ECS events from the Metrics cluster.  This will
allow us to capture and alarm on ECS error events.
* #246

feat: add ECS event logging for Metrics cluster

---

aws/ecs/cloudwatch_ecs_events.tf

Add a CloudWatch alarm if an ECS warning or error event is detected.
This will cover cases like task `OutOfMemoryErrors` that are not caught
by the current CloudWatch metric alarms.
* #246

feat: CloudWatch alarm if ECS warn/error event

---

aws/ecs/cloudwatch_ecs_events.tf

Use a consistent name for the ECS warn/error metric filter
so that it can be easily referenced by the CloudWatch alarm.
⚠️ &nbsp;Change was applied locally to test.
* #246

fix: ECS warn/error metric filter name

---

env/production/ecs/terragrunt.hcl

This is deploying the in-app metrics fix that removes
the double Datetime conversion as the Pandas
dataframe is being created.
* cds-snc/covid-alert-metrics-etl#177

fix: in-app metrics OutOfMemory errors

---

.github/workflows/security-scan.yml
env/production/ecs/terragrunt.hcl

Update the metrics ECS tasks with the fix for dates that
are not within Panda's parseable range.

fix: metrics tasks unparseable dates

---

README.md

Covid Alert is now retired.
Updated README looks like so:
https://github.com/cds-snc/covid-alert-metrics-terraform/blob/docs/decomm/README.md

docs: add retired message to README

---

aws/cloudwatch_alarms/api_gateway.tf

This alarm is no longer required.

chore: delete API gateway min invocation alarm
